### ISSUE TITLE
versionCode not increased

### ISSUE THREAD

**Issue by IzzySoft** [kevinboone/androidmusicserver#5]
Great to see a new release, thanks! But looks like you forgot to increase the [`versionCode`](https://github.com/kevinboone/androidmusicserver/blob/master/app/src/main/AndroidManifest.xml#L4), the new APK has the same as the previous one. As `versionCode` is what Android uses to tell releases apart, please don't forget increasing it with each release :wink:

**Comment by kevinboone** [comment]
Sorry -- just shows how out-of-practice I am with Android development :/ To be honest, it's getting increasingly hard to maintain this app, as many devices aggressively close services that don't have a UI visible.

**Comment by IzzySoft** [comment]
I've heard that. I'm not an Android dev, so I can only tell by hear-say what possible solutions are – which you most likely already have investigated: keeping a permanent notification open, or use something called "[don't kill my app](https://dontkillmyapp.com/)". Then there's something with "foreground services", but that you most likely have tried already…
