### ISSUE TITLE
Certificate issue

### ISSUE THREAD

**Issue by IzzySoft** [kevinboone/androidmusicserver#6]
A scan ([see here](https://gitlab.com/IzzyOnDroid/repo/-/issues/477) for details and background) just revealed the APKs at your releases are signed using an expired debug key ("denyAfter 2019-01-01"). As that has security implications, may I ask you to please switch to a proper release key, and provide the corresponding APK signed with it? Thanks in advance!

**Comment by kevinboone** [comment]
I've added a signed APK to the apk/ directory. Do I need to do more than that? 

I have to point out that this doesn't change the fact that this is ancient code and, although it does build with the latest Android SDK, it doesn't work terribly well on modern devices.

**Comment by IzzySoft** [comment]
Thanks for your fast response!!!

> I've added a signed APK to the apk/ directory. Do I need to do more than that?

Could you please use a release key instead of a debug key? Previous key:

```
Signer #1 certificate DN: C=US, O=Android, CN=Android Debug
Signer #1 certificate SHA-256 digest: ce6d0e5f41bd011f5123734ea4b84647f9e5bca844475bc26453ee41f2bef172
Signer #1 certificate SHA-1 digest: 4c4d70df17e7ebc48c972ac303ddf573d331c938
Signer #1 certificate MD5 digest: 826938855465a9cbe00eab2b58849548
Signer #1 key algorithm: RSA
```

Current key:

```
Signer #1 certificate DN: C=US, O=Android, CN=Android Debug
Signer #1 certificate SHA-256 digest: b2148cf9b0610d3693a8ecfd4d593819f7d4cd12128a247751da75109e395746
Signer #1 certificate SHA-1 digest: b3ab8afda1a7ce4c73df6cbddb48622725b1da50
Signer #1 certificate MD5 digest: 1830387bacc24157d7ef7e9755118e83
Signer #1 key algorithm: RSA
```

It is again a debug key (`CN=Android Debug`), so in about a year (debug keys to my knowledge expire after 365 days) it will have the very same problem again – and then everyone has to uninstall and re-install once more, as the changed key does not allow updating. Btw, you can attach the APK to its corresponding release instead of checking it into the repo itself, if you wish :wink: To do so, just go to [releases](https://github.com/kevinboone/androidmusicserver/releases), edit the corresponding release, and Github should allow you to attach files.

> I have to point out that this doesn't change the fact that this is ancient code and, although it does build with the latest Android SDK, it doesn't work terribly well on modern devices.

Yes, I'm aware of that. My repo (where [your app is listed](https://apt.izzysoft.de/packages/net.kevinboone.androidmediaserver/)) wants to help people to keep their devices useful as long as possible, so count those with older devices as the "main group" your app is intended for :wink:

That said, if you wish to emphasize this, you can mention it [in the `full_description.txt`](https://github.com/kevinboone/androidmusicserver/blob/master/fastlane/metadata/android/en-US/full_description.txt), which is pulled along with any new releases should it have changed.

**Comment by kevinboone** [comment]
Sorry -- but I have to ask: are you testing the new file apk/app-release.apk?

When I run 'jarsigner -verify' on it, I see this:

- Signed by "CN=Kevin Boone, OU=Android, O=PawPrint Software, L=London, ST=London, C=GB"
    Digest algorithm: SHA1 (weak)
    Signature algorithm: SHA1withRSA (weak), 2048-bit key

Conceivably I've confused everything by using a new name :/

**Comment by IzzySoft** [comment]
> Sorry -- but I have to ask: are you testing the new file apk/app-release.apk?

Let me check what my updater pulls… Ah, no filter, so randomly the "newest APK in that location", yikes. Apologies then! Let me fix that on my end:

```yaml
GHDownloadDir: https://github.com/kevinboone/androidmusicserver/blob/master/apk
ApkMatch: /release/i
ApkIgnore: /debug/i
```

(just putting in both to be sure). Now, let me trigger another update… Right! Now it fits – was all my fault this time! Making a note to check my updater why it doesn't do that automatically there (it does when picking APKs from tagged releases, so I was assuming I had set that up here as well – it's rather rare that APKs are placed *inside* repositories).

I've pinned the new key now (APKs are only accepted into my repo if their certificate matches).

Thanks again – and my sincere apologies to the lapsus of my updater picking the wrong APK. Won't repeat!

PS: Should you one day switch and place APKs into the releases (to keep your repo trim), please drop me a note so I tell my updater :wink:

**Comment by IzzySoft** [comment]
> Making a note to check my updater why it doesn't do that automatically there

Fixed: it does so now (hopefully) :smiley:

**Comment by kevinboone** [comment]
I wouldn't normally put binaries into a repository, but these are comparatively tiny, and (within the scope of the project) platform-independent. It's easier for me to commit them with the source than to main separate binary releases. Sorry if that's a pain :)

**Comment by IzzySoft** [comment]
If you prefer it that way, it's fine. In this case even helped me discovering a bug in my updater (OK, one that wouldn't have any effect if APKs were always outside the repo). Works now, so no prob :smiley: Thanks!
